platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MHAppIndexing_Example', :exclusive => true do
  pod 'MHAppIndexing', :path => '../'
end

target 'MHAppIndexing_Tests', :exclusive => true do
  pod 'MHAppIndexing', :path => '../'

  pod 'Quick', '~> 0.9.2'
  pod 'Nimble', '4.0.1'
end
